// Generated by scripts/generate-content-index.mjs. Do not edit.
import type { ContentEntry } from "./types";

export const CONTENT_ENTRIES: ContentEntry[] = [
  {
    "title": "秋招不是一场考试，而是一段重新认识自己的旅程",
    "slug": "autumn-recruiting-journey",
    "type": "jobs",
    "date": "2026-07-18",
    "summary": "在一次次投递、面试和复盘中，重新确认自己真正想解决的问题。",
    "tags": [
      "秋招",
      "选择",
      "成长"
    ],
    "related": [
      "2026-07-22"
    ],
    "status": "published",
    "body": "秋招最容易制造的错觉，是把每一次面试都看成一张即时判分的试卷。后来我才发现，真正值得记录的并不是通过率，而是每次回答之后暴露出的认知边界。\n\n我开始把复盘分成三层：事实是否准确，推理是否完整，表达是否让对方看见我做决定的依据。结果仍然重要，但它不再是唯一的坐标。\n\n这段旅程最终让我更具体地理解自己：我希望继续做具身智能，也愿意在数据、模型与真实系统之间承担那些不够光鲜却决定成败的工作。"
  },
  {
    "title": "实习第 47 天：第一次把一个模型真正跑进业务",
    "slug": "day-47-model-in-production",
    "type": "internship",
    "date": "2026-06-23",
    "summary": "从离线指标到线上约束，记录模型第一次进入真实业务链路时学到的事。",
    "tags": [
      "实习",
      "模型部署",
      "工程"
    ],
    "related": [
      "unitacvla-reading"
    ],
    "status": "published",
    "body": "第 47 天，模型终于不再只活在 notebook 的曲线里。接口延迟、失败重试、输入漂移和回滚策略一起出现，迫使我重新回答“模型可用”到底意味着什么。\n\n离线实验只证明了一种可能，业务系统要求的是稳定、可解释、可恢复。我们给关键路径补上监控，把置信度异常变成明确的降级条件，也第一次认真计算每一次推理的时间预算。\n\n上线没有带来戏剧性的庆祝，但日志里稳定落下的每个请求，都比一张更漂亮的指标表更有真实感。"
  },
  {
    "title": "UniTacVLA：触觉如何进入动作生成",
    "slug": "unitacvla-reading",
    "type": "papers",
    "date": "2026-05-09",
    "summary": "从动作条件化视角理解视觉、语言与触觉如何共同影响策略输出。",
    "tags": [
      "VLA",
      "触觉",
      "机器人学习"
    ],
    "related": [
      "2026-07-22"
    ],
    "status": "published",
    "authors": [
      "UniTacVLA Team"
    ],
    "venue": "arXiv",
    "year": 2026,
    "topics": [
      "multimodal-policy",
      "tactile-sensing",
      "action-generation"
    ],
    "body": "UniTacVLA 最值得追问的并不是“多加了一种模态”，而是触觉信息在什么时间尺度上改变动作生成。策略可以写成 $\\pi(a_t\\mid o_{\\le t})$，但这里的观测已经不只是图像和指令，还包含接触发生之后才出现的局部反馈。\n\n如果把视觉理解为接触前的全局先验，触觉更像接触后的高频校正信号。两者需要在动作序列中承担不同职责：\n\n$$\na_t = f_\\theta(v_{\\le t}, l, \\tau_{\\le t})\n$$\n\n这也意味着评估不能只看任务是否最终完成，还要观察接触后的恢复动作、力控制稳定性，以及触觉缺失时策略的退化方式。\n\n| 信号 | 策略职责 | 典型时间尺度 |\n| --- | --- | --- |\n| 视觉 | 接触前的全局先验 | 低频 |\n| 触觉 | 接触后的局部校正 | 高频 |\n\n```text\nobservation -> multimodal policy -> action sequence -> tactile correction\n```",
    "readAt": "2026-05-10",
    "paperUrl": "https://arxiv.org/",
    "readingStatus": "reviewed"
  },
  {
    "title": "关于长期主义，我最近改变的三个看法",
    "slug": "2026-07-22",
    "type": "reflections",
    "date": "2026-07-22",
    "summary": "长期主义不是坚持同一条路径，而是持续保留校准方向的能力。",
    "tags": [
      "长期主义",
      "复盘",
      "日常思考"
    ],
    "related": [
      "unitacvla-reading",
      "autumn-recruiting-journey"
    ],
    "status": "published",
    "body": "过去我把长期主义理解为“选定以后一直坚持”，现在更愿意把它理解成三件事：保留长期问题，允许短期路径变化；积累能够复用的判断，而不只是结果；定期用新证据校准自己。\n\n读 `unitacvla-reading` 时，我再次意识到这种校准并不抽象。一个系统要在接触之后根据触觉修正动作，人也需要在真正经历之后更新原来的判断。\n\n所以坚持不再意味着拒绝变化，而是持续回到那个值得追问的问题，并诚实地承认下一步可能和昨天设想的不一样。"
  },
  {
    "title": "把问题留在桌面上",
    "slug": "2026-07-21",
    "type": "reflections",
    "date": "2026-07-21",
    "summary": "有些问题不需要当天回答，但值得留在每天都能看见的地方。",
    "tags": [
      "日常思考",
      "复盘"
    ],
    "related": [],
    "status": "published",
    "body": "过去我总想在一天结束前给每件事一个结论。后来才明白，真正重要的问题往往需要在生活里放得更久。\n\n把问题留在桌面上，不代表拖延回答，而是允许新的证据慢慢出现。今天能做的，是把它写清楚，然后带着它继续生活。"
  }
];
