// Generated by scripts/generate-content-index.mjs. Do not edit.
import type { ContentEntry } from "./types";

export const LEGACY_CONTENT_ENTRIES: ContentEntry[] = [
  {
    "title": "Fixture",
    "slug": "private-draft",
    "type": "jobs",
    "date": "2026-07-20",
    "summary": "Fixture summary",
    "tags": [
      "test"
    ],
    "related": [],
    "status": "draft",
    "company": "Example Robotics",
    "role": "具身智能算法工程师",
    "body": "Body",
    "applicationStage": "interview"
  },
  {
    "title": "Fixture",
    "slug": "fixture",
    "type": "jobs",
    "date": "2026-07-20",
    "summary": "Fixture summary",
    "tags": [
      "test"
    ],
    "related": [],
    "status": "published",
    "company": "Example Robotics",
    "role": "具身智能算法工程师",
    "body": "Body",
    "applicationStage": "interview"
  }
];
