// Generated by scripts/generate-content-index.mjs. Do not edit.
import type { ContentEntry } from "./types";

export const LEGACY_CONTENT_ENTRIES: ContentEntry[] = [
  {
    "title": "秋招不是一场考试，而是一段重新认识自己的旅程",
    "slug": "autumn-recruiting-journey",
    "type": "jobs",
    "date": "2026-07-18",
    "summary": "在一次次投递、面试和复盘中，重新确认自己真正想解决的问题。",
    "tags": [
      "秋招",
      "选择",
      "成长"
    ],
    "related": [
      "2026-07-22"
    ],
    "status": "published",
    "company": "个人秋招总览",
    "role": "具身智能算法工程师",
    "location": "全国",
    "body": "## 投递\n\n秋招最容易制造的错觉，是把每一次面试都看成一张即时判分的试卷。后来我才发现，真正值得记录的并不是通过率，而是每次回答之后暴露出的认知边界。\n\n## 面试\n\n我开始把复盘分成三层：事实是否准确，推理是否完整，表达是否让对方看见我做决定的依据。结果仍然重要，但它不再是唯一的坐标。\n\n## 最终复盘\n\n这段旅程最终让我更具体地理解自己：我希望继续做具身智能，也愿意在数据、模型与真实系统之间承担那些不够光鲜却决定成败的工作。",
    "applicationStage": "interview",
    "appliedAt": "2026-07-18",
    "nextAction": "持续复盘面试并补强系统落地表达"
  },
  {
    "title": "FINAL REVIEW PRIVATE DRAFT",
    "slug": "final-review-private-draft",
    "type": "jobs",
    "date": "2026-07-23",
    "summary": "这个合法草稿只用于验证构建索引不会泄露未发布内容。",
    "tags": [
      "draft-privacy"
    ],
    "related": [],
    "status": "draft",
    "company": "PRIVATE TEST",
    "role": "草稿隔离验证",
    "body": "这段正文不得出现在生成索引、路由、搜索、近期内容或关联内容中。",
    "applicationStage": "closed"
  },
  {
    "title": "实习第 47 天：第一次把一个模型真正跑进业务",
    "slug": "day-47-model-in-production",
    "type": "internship",
    "date": "2026-06-23",
    "summary": "从离线指标到线上约束，记录模型第一次进入真实业务链路时学到的事。",
    "tags": [
      "实习",
      "模型部署",
      "工程"
    ],
    "related": [
      "unitacvla-reading"
    ],
    "status": "published",
    "body": "第 47 天，模型终于不再只活在 notebook 的曲线里。接口延迟、失败重试、输入漂移和回滚策略一起出现，迫使我重新回答“模型可用”到底意味着什么。\n\n离线实验只证明了一种可能，业务系统要求的是稳定、可解释、可恢复。我们给关键路径补上监控，把置信度异常变成明确的降级条件，也第一次认真计算每一次推理的时间预算。\n\n上线没有带来戏剧性的庆祝，但日志里稳定落下的每个请求，都比一张更漂亮的指标表更有真实感。"
  },
  {
    "title": "论文阅读标题",
    "slug": "paper-reading-note",
    "type": "papers",
    "date": "2026-07-23",
    "summary": "一句话概括论文的核心问题。",
    "tags": [
      "论文阅读"
    ],
    "related": [],
    "status": "draft",
    "authors": [],
    "venue": "arXiv",
    "year": 2026,
    "topics": [],
    "body": "## 粗读记录\n\n### 核心问题\n\n模型只负责归一化的输入和输出，而反归一化则需要给予别的类进行外层包装即可\n\n如何创建一个合格的基类：\n\n- 如何获取数据\n- 如何计算损失\n- 如何反传梯度（优化器）\n- 训练循环/梯度积累/混合精度等辅助函数\n\n### 继承类\n\n开放四个方法\n\n- forward\n- get_action\n- lazy_joint_video_action\n- prepare_input\n\n### Python 语法补充\n\n#### BatchFeature\n\nHuggingFace transformers 库提供的一个数据容器类，能自动把 list/numpy 转成 tensor。\n\n```python\nfrom transformers.feature_extraction_utils import BatchFeature\n\n# 本质上就是一个 dict，但多了自动类型转换能力\nbatch = BatchFeature({\n    \"loss\": torch.tensor(0.5),\n    \"action_pred\": torch.randn(4, 24, 14),\n    \"video_pred\": torch.randn(4, 33, 16),\n})\n```\n\n#### @abstractmethod 装饰器\n\n强制子类必须实现特定的方法。",
    "readAt": "2026-07-23",
    "paperUrl": "https://example.com/paper",
    "readingStatus": "in_progress",
    "readingMethods": [
      "skim"
    ]
  },
  {
    "title": "UniTacVLA：触觉如何进入动作生成",
    "slug": "unitacvla-reading",
    "type": "papers",
    "date": "2026-05-09",
    "summary": "从动作条件化视角理解视觉、语言与触觉如何共同影响策略输出。",
    "tags": [
      "VLA",
      "触觉",
      "机器人学习"
    ],
    "related": [
      "2026-07-22"
    ],
    "status": "published",
    "authors": [
      "UniTacVLA Team"
    ],
    "venue": "arXiv",
    "year": 2026,
    "topics": [
      "multimodal-policy",
      "tactile-sensing",
      "action-generation"
    ],
    "body": "## 细读记录\n\nUniTacVLA 最值得追问的并不是“多加了一种模态”，而是触觉信息在什么时间尺度上改变动作生成。策略可以写成 $\\pi(a_t\\mid o_{\\le t})$，但这里的观测已经不只是图像和指令，还包含接触发生之后才出现的局部反馈。\n\n如果把视觉理解为接触前的全局先验，触觉更像接触后的高频校正信号。两者需要在动作序列中承担不同职责：\n\n$$\na_t = f_\\theta(v_{\\le t}, l, \\tau_{\\le t})\n$$\n\n这也意味着评估不能只看任务是否最终完成，还要观察接触后的恢复动作、力控制稳定性，以及触觉缺失时策略的退化方式。\n\n| 信号 | 策略职责 | 典型时间尺度 |\n| --- | --- | --- |\n| 视觉 | 接触前的全局先验 | 低频 |\n| 触觉 | 接触后的局部校正 | 高频 |\n\n```text\nobservation -> multimodal policy -> action sequence -> tactile correction\n```\n\n## 阅读总结\n\n这篇工作真正有价值的地方，是把触觉从附加模态转化为接触后的动作校正依据。后续阅读同类工作时，应重点比较触觉进入策略的时间尺度、融合位置和缺失模态下的退化方式。",
    "readAt": "2026-05-10",
    "paperUrl": "https://arxiv.org/",
    "readingStatus": "completed",
    "readingMethods": [
      "deep",
      "synthesis"
    ]
  },
  {
    "title": "今日感悟",
    "slug": "2026-07-27",
    "type": "reflections",
    "date": "2026-07-27",
    "summary": "一句话概括今天的思考。",
    "tags": [
      "日常思考"
    ],
    "related": [],
    "status": "draft",
    "body": "## 总揽\n\n如何使用 grill with docs（grill me 项目化版本）：它不仅会在写代码前拷问需求，还会把你的计划与项目里的 `CONTEXT.md`、`docs/adr/` 对照起来，发现术语冲突、代码事实和架构决策缺口。\n\n## 怎么安装\n\n- `/setup-matt-pocock-skills`：询问 `CONTEXT.md` 和 ADR（Architecture Decision Record）目录放在哪里。\n\n```md\nOnly offer to create an ADR when all three are true:\n\nHard to reverse — the cost of changing your mind later is meaningful\nSurprising without context — a future reader will wonder \"why did they do it this way?\"\nThe result of a real trade-off — there were genuine alternatives\n```\n\n## 怎么用\n\n- 描述想做的事情。\n- 运行 `/grill-with-docs`。\n- Claude 先扫描 `CONTEXT.md` 和 `docs/adr/`，把现有术语和决策装进上下文。\n- 开始拷问。\n\n```md\n你用的词和 CONTEXT.md 冲突 → 当场指出\n你用了模糊词（比如「账户」既可能是 Customer 也可能是 User）→ 让你二选一并落进文档\n你说的行为和现有代码矛盾 → 指出冲突\n```\n\n- 决策达成时同步更新 `CONTEXT.md`。\n- 遇到关键且不可逆的决策时，询问是否生成 ADR。"
  },
  {
    "title": "关于长期主义，我最近改变的三个看法",
    "slug": "2026-07-22",
    "type": "reflections",
    "date": "2026-07-22",
    "summary": "长期主义不是坚持同一条路径，而是持续保留校准方向的能力。",
    "tags": [
      "长期主义",
      "复盘",
      "日常思考"
    ],
    "related": [
      "unitacvla-reading",
      "autumn-recruiting-journey"
    ],
    "status": "published",
    "body": "过去我把长期主义理解为“选定以后一直坚持”，现在更愿意把它理解成三件事：保留长期问题，允许短期路径变化；积累能够复用的判断，而不只是结果；定期用新证据校准自己。\n\n读 `unitacvla-reading` 时，我再次意识到这种校准并不抽象。一个系统要在接触之后根据触觉修正动作，人也需要在真正经历之后更新原来的判断。\n\n所以坚持不再意味着拒绝变化，而是持续回到那个值得追问的问题，并诚实地承认下一步可能和昨天设想的不一样。"
  },
  {
    "title": "把问题留在桌面上",
    "slug": "2026-07-21",
    "type": "reflections",
    "date": "2026-07-21",
    "summary": "有些问题不需要当天回答，但值得留在每天都能看见的地方。",
    "tags": [
      "日常思考",
      "复盘"
    ],
    "related": [],
    "status": "published",
    "body": "过去我总想在一天结束前给每件事一个结论。后来才明白，真正重要的问题往往需要在生活里放得更久。\n\n把问题留在桌面上，不代表拖延回答，而是允许新的证据慢慢出现。今天能做的，是把它写清楚，然后带着它继续生活。"
  }
];
